export const ADD_TODO = "ADD_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const FINISHED_TODO = "FINISHED_TODO";
export const NOT_FINISHED_TODO = "NOT_FINISHED_TODO";
export const UPDATE_TODO = "UPDATE_TODO";
export const UPDATE_TODO_STATUS = "UPDATE_TODO_STATUS";
